services:
  postgres:
    image: 'postgres:latest'
    container_name: jpa_demo
    environment:
      POSTGRES_DB: jpa_demo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

